### ISSUE TITLE
video

### ISSUE THREAD

**Issue by D4Fi** [D4Fi/Scratch#1]
[Gravação de tela de 01-08-2023 00:39:17.webm](https://github.com/D4Fi/Scratch/assets/139288494/45abec8f-4c5f-4f5f-a80d-687e9675ce16)

**Comment by Adeema-Amir** [comment]
hey D4FI

**Comment by Adeema-Amir** [comment]
what a bad name D4FI

**Comment by Adeema-Amir** [comment]
what is the meaning of D4FI
